#!/bin/bash

# read-multiple: read multiple values from keyboard

echo -n "Enter one or more values -> "
read val1 val2 val3 val4 val5

cat << _EOF_
val1 = $val1
val2 = $val2
val3 = $val3
val4 = $val4
val5 = $val5
_EOF_


read -p "Enter one value(Using Reply) -> "
echo "REPLY = $REPLY"
