#!/bin/bash

# test-integer: evaluate the value of an integer.

echo -n "Please enter an integer -> "
read INT

if [[ "$INT" =~ ^-?[0-9]+$  ]]; then
	echo "INT is an intger."
else 
	echo "INT is not an integer." >&2
	exit 1
fi

if [ -z "$INT" ]; then
	echo "INT is empty." >&2
	exit 1
fi

if ((INT == 0)); then
	echo "INT is zero."
else
	if ((INT < 0)); then
		echo "INT is negative."
	else 
		echo "INT is positive."
	fi
	if (( ((INT%2)) == 0  )); then
		echo "INT is even."
	else 
		echo "INT is odd."
	fi
fi
